/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{html,js,ts,tsx}",
    ],
    theme: {
        extend: {
            gridTemplateColumns: {
                "fiftyfifty": "45% 45%",
                "widermiddle-3": "25% 30% 25%",
            },
            gridTemplateRows: {
                "colwisedown-8": "1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr",
                "colwisedown-7": "1fr 1fr 1fr 1fr 1fr 1fr 1fr",
                "colwisedown-6": "1fr 1fr 1fr 1fr 1fr 1fr",
                "colwisedown-5": "1fr 1fr 1fr 1fr 1fr",
                "colwisedown-4": "1fr 1fr 1fr 1fr",
                "colwisedown-3": "1fr 1fr 1fr",
                "colwisedown-2": "1fr 1fr",
            },
            width: {
                "100": "25rem", //400 
                "128": "32rem", //512
                "152": "38rem", //608
                "176": "44rem", //704
                "208": "52rem", //832
                "224": "56rem", //896
                "256": "64rem", //1024
                "280": "70rem", //1120
            },
            minWidth: {
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "20": "5rem",
                "24": "6rem",
                "28": "7rem",
                "32": "8rem",
                "36": "9rem",
                "40": "10rem",
                "44": "11rem",
                "48": "12rem",
                "52": "13rem",
                "56": "14rem",
                "60": "15rem",
                "64": "16rem",
                "72": "18rem",
                "80": "20rem",
                "96": "24rem",
                "100": "25rem",                
                "128": "32rem",
                "152": "38rem",
                "176": "44rem",
                "208": "52rem",
                "224": "56rem",
                "256": "64rem",
                "280": "70rem"
            },
            maxWidth: {
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "20": "5rem",
                "24": "6rem",
                "28": "7rem",
                "32": "8rem",
                "36": "9rem",
                "40": "10rem",
                "44": "11rem",
                "48": "12rem",
                "52": "13rem",
                "56": "14rem",
                "60": "15rem",
                "64": "16rem",
                "72": "18rem",
                "80": "20rem",
                "96": "24rem",
                "100": "25rem",
                "128": "32rem",
                "152": "38rem",
                "176": "44rem",
                "208": "52rem",
                "224": "56rem",
                "256": "64rem",
                "280": "70rem"
            },
            height: {
                "100": "25rem", 
                "128": "32rem",
                "152": "38rem",
                "176": "44rem",
                "208": "52rem",
                "224": "56rem",
                "256": "64rem",
                "280": "70rem"
            },
            minHeight: {
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "20": "5rem",
                "24": "6rem",
                "28": "7rem",
                "32": "8rem",
                "36": "9rem",
                "40": "10rem",
                "44": "11rem",
                "48": "12rem",
                "52": "13rem",
                "56": "14rem",
                "60": "15rem",
                "64": "16rem",
                "72": "18rem",
                "80": "20rem",
                "96": "24rem",
                "100": "25rem",
                "128": "32rem",
                "152": "38rem",
                "176": "44rem",
                "208": "52rem",
                "224": "56rem",
                "256": "64rem",
                "280": "70rem"
            },
            maxHeight: {
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "20": "5rem",
                "24": "6rem",
                "28": "7rem",
                "32": "8rem",
                "36": "9rem",
                "40": "10rem",
                "44": "11rem",
                "48": "12rem",
                "52": "13rem",
                "56": "14rem",
                "60": "15rem",
                "64": "16rem",
                "72": "18rem",
                "80": "20rem",
                "96": "24rem",
                "128": "32rem",
                "152": "38rem",
                "176": "44rem",
                "208": "52rem",
                "224": "56rem",
                "256": "64rem",
                "280": "70rem"
            },
            screens: {
                "4xl": "1920px",
                "3xl": "1680px",
                "xs": "576px",
                "2xs": "512px",
                "3xs": "448px",
                "4xs": "384px",
                "5xs": "320px",

            },
            colors: {
                highlight: {
                    "turquoise": "rgb(var(--color-highlight-turquoise) / <alpha-value>)",
                    "purple": "rgb(var(--color-primary-300) / <alpha-value>)",
                    "gray": "rgb(var(--color-neutral-350) / <alpha-value>)",
                },
                neutral: {
                    "10": "rgb(var(--color-neutral-10) / <alpha-value>)",
                    "20": "rgb(var(--color-neutral-20) / <alpha-value>)",
                    "30": "rgb(var(--color-neutral-30) / <alpha-value>)",
                    "40": "rgb(var(--color-neutral-40) / <alpha-value>)",
                    "50": "rgb(var(--color-neutral-50) / <alpha-value>)",
                    "100": "rgb(var(--color-neutral-100) / <alpha-value>)",
                    "150": "rgb(var(--color-neutral-150) / <alpha-value>)",
                    "200": "rgb(var(--color-neutral-200) / <alpha-value>)",
                    "350": "rgb(var(--color-neutral-350) / <alpha-value>)",
                    "360": "rgb(var(--color-neutral-360) / <alpha-value>)",
                    "400": "rgb(var(--color-neutral-400) / <alpha-value>)",
                    "410": "rgb(var(--color-neutral-410) / <alpha-value>)",
                    DEFAULT: "rgb(var(--color-neutral-400) / <alpha-value>)",
                },
                primary: {
                    "50": "rgb(var(--color-primary-50) / <alpha-value>)",
                    "100": "rgb(var(--color-primary-100) / <alpha-value>)",
                    "200": "rgb(var(--color-primary-200) / <alpha-value>)",
                    "250": "rgb(var(--color-primary-250) / <alpha-value>)",
                    "300": "rgb(var(--color-primary-300) / <alpha-value>)",
                    "350": "rgb(var(--color-primary-350) / <alpha-value>)",
                    "400": "rgb(var(--color-primary-400) / <alpha-value>)",
                    DEFAULT: "rgb(var(--color-primary-200) / <alpha-value>)",
                },
                success: {
                    "50": "rgb(var(--color-success-50) / <alpha-value>)",
                    "100": "rgb(var(--color-success-100) / <alpha-value>)",
                },
                warning: {
                    "50": "rgb(var(--color-warning-50) / <alpha-value>)",
                    "100": "rgb(var(--color-warning-100) / <alpha-value>)",
                    "200": "rgb(var(--color-warning-200) / <alpha-value>)",
                    "300": "rgb(var(--color-warning-300) / <alpha-value>)",
                },
                destructive: {
                    "50": "rgb(var(--color-destructive-50) / <alpha-value>)",
                    "100": "rgb(var(--color-destructive-100) / <alpha-value>)",
                    "200": "rgb(var(--color-destructive-200) / <alpha-value>)",
                    "300": "rgb(var(--color-destructive-300) / <alpha-value>)",
                },
                pill: {
                    "1": "rgb(var(--color-pill-1) / <alpha-value>)",
                    "2": "rgb(var(--color-pill-2) / <alpha-value>)",
                    "3": "rgb(var(--color-pill-3) / <alpha-value>)",
                    "4": "rgb(var(--color-pill-4) / <alpha-value>)",
                    "5": "rgb(var(--color-pill-5) / <alpha-value>)",
                    "6": "rgb(var(--color-pill-6) / <alpha-value>)",
                    "7": "rgb(var(--color-pill-7) / <alpha-value>)",
                    "8": "rgb(var(--color-pill-8) / <alpha-value>)",
                    "9": "rgb(var(--color-pill-9) / <alpha-value>)",
                },
            }
        },
    },
    plugins: [require('@tailwindcss/forms'),],
}